const Jobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "TechNova Inc.",
    logo: "https://ui-avatars.com/api/?name=TechNova+Inc.&background=random",
    location: "Remote",
    type: "Full-Time",
    salary: "₹8,00,000 - ₹12,00,000 / year",
    experience: "2+ years",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    postedDate: "2025-05-10",
    description: "Looking for a React developer to build and maintain UI components. Must have experience with REST APIs."
  },
  {
    id: 2,
    title: "Backend Engineer",
    company: "DataCrate Solutions",
    logo: "https://ui-avatars.com/api/?name=DataCrate+Solutions&background=random",
    location: "Pune, India",
    type: "Full-Time",
    salary: "₹10,00,000 - ₹15,00,000 / year",
    experience: "3+ years",
    skills: ["Node.js", "Express", "MongoDB", "Docker"],
    postedDate: "2025-05-15",
    description: "Seeking backend engineer with strong Node.js and MongoDB skills. Experience with DevOps is a plus."
  },
  {
    id: 3,
    title: "UI/UX Designer",
    company: "DesignHive Studio",
    logo: "https://ui-avatars.com/api/?name=DesignHive+Studio&background=random",
    location: "Bengaluru, India",
    type: "Contract",
    salary: "₹5,00,000 - ₹8,00,000 / year",
    experience: "1+ year",
    skills: ["Figma", "Adobe XD", "Wireframing", "Prototyping"],
    postedDate: "2025-05-18",
    description: "Join our design team to create intuitive user experiences. A portfolio is required."
  },
  {
    id: 4,
    title: "DevOps Engineer",
    company: "CloudStack Ltd.",
    logo: "https://ui-avatars.com/api/?name=CloudStack+Ltd.&background=random",
    location: "Hyderabad, India",
    type: "Full-Time",
    salary: "₹12,00,000 - ₹18,00,000 / year",
    experience: "4+ years",
    skills: ["AWS", "Kubernetes", "CI/CD", "Terraform"],
    postedDate: "2025-05-20",
    description: "Manage cloud infrastructure, automate deployments, and ensure scalability."
  },
  {
    id: 5,
    title: "Intern - Software Engineer",
    company: "StartupVerse",
    logo: "https://ui-avatars.com/api/?name=StartupVerse&background=random",
    location: "Remote",
    type: "Internship",
    salary: "₹15,000 / month",
    experience: "Fresher",
    skills: ["JavaScript", "Git", "Basic Web Dev"],
    postedDate: "2025-05-21",
    description: "Software development internship for freshers. Learn and contribute to real-world projects."
  },
  {
    id: 6,
    title: "Mobile App Developer",
    company: "Appify",
    logo: "https://ui-avatars.com/api/?name=Appify&background=random",
    location: "Chennai, India",
    type: "Full-Time",
    salary: "₹9,00,000 - ₹13,00,000 / year",
    experience: "2+ years",
    skills: ["Flutter", "Firebase", "Android/iOS"],
    postedDate: "2025-05-11",
    description: "Develop cross-platform mobile apps using Flutter and Firebase. Experience with iOS/Android deployment preferred."
  },
  {
    id: 7,
    title: "Machine Learning Engineer",
    company: "NeuroAI",
    logo: "https://ui-avatars.com/api/?name=NeuroAI&background=random",
    location: "Mumbai, India",
    type: "Full-Time",
    salary: "₹14,00,000 - ₹20,00,000 / year",
    experience: "3+ years",
    skills: ["Python", "TensorFlow", "Pandas", "Scikit-learn"],
    postedDate: "2025-05-13",
    description: "Work on ML models for finance and healthcare industries. Must have experience in real-time data pipelines."
  },
  {
    id: 8,
    title: "Technical Content Writer",
    company: "WriteByte",
    logo: "https://ui-avatars.com/api/?name=WriteByte&background=random",
    location: "Remote",
    type: "Part-Time",
    salary: "₹30,000 - ₹50,000 / month",
    experience: "1+ year",
    skills: ["Technical Writing", "Markdown", "SEO", "APIs"],
    postedDate: "2025-05-14",
    description: "Write blog posts, documentation, and tutorials for technical products. Strong writing and research skills needed."
  },
  {
    id: 9,
    title: "QA Engineer",
    company: "BugTrack Systems",
    logo: "https://ui-avatars.com/api/?name=BugTrack+Systems&background=random",
    location: "Delhi, India",
    type: "Full-Time",
    salary: "₹6,00,000 - ₹9,00,000 / year",
    experience: "2+ years",
    skills: ["Manual Testing", "Automation", "Selenium", "JIRA"],
    postedDate: "2025-05-16",
    description: "Responsible for testing software products manually and through automation. Should be familiar with bug tracking tools."
  },
  {
    id: 10,
    title: "System Administrator",
    company: "InfraTech Corp",
    logo: "https://ui-avatars.com/api/?name=InfraTech+Corp&background=random",
    location: "Kolkata, India",
    type: "Full-Time",
    salary: "₹7,00,000 - ₹10,00,000 / year",
    experience: "3+ years",
    skills: ["Linux", "Networking", "Security", "Bash"],
    postedDate: "2025-05-17",
    description: "Maintain and monitor company infrastructure. Manage backups, servers, and ensure uptime for all systems."
  }
];

module.exports = Jobs;
